apiVersion: v1
kind: Service
metadata:
  name: ascwebsvc
  namespace: ascdev
  labels:
    version: test
spec:
  selector: 
    app: ascweb
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 443
    protocol: TCP
    name: https
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ascwebdep
  namespace: ascdev
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ascweb
    spec:
      containers:
      - name: ascreact
        image: ascregistry-on.azurecr.io/ascreact:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 30
          periodSeconds: 30
          failureThreshold: 10
      imagePullSecrets:
        - name: ascreg