// ------------------------------------
// Constants
// ------------------------------------
export const REGISTER_USER_REQUESTED = 'REGISTER_USER_REQUESTED';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';

export const LOGIN_EMAIL_REQUESTED = 'LOGIN_EMAIL_REQUESTED';
export const LOGIN_EMAIL_SUCCESS = 'LOGIN_EMAIL_SUCCESS';
export const LOGIN_EMAIL_FAILED = 'LOGIN_EMAIL_FAILED';

export const SAVE_PROFILE_REQUESTED = 'SAVE_PROFILE_REQUESTED';
export const SAVE_PROFILE_SUCCESS = 'SAVE_PROFILE_SUCCESS';
export const SAVE_PROFILE_FAILED = 'SAVE_PROFILE_FAILED';

export const UPDATE_PROFILE_REQUESTED = 'UPDATE_PROFILE_REQUESTED';
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILED = 'UPDATE_PROFILE_FAILED';

export const GET_PROFILE_REQUESTED = 'GET_PROFILE_REQUESTED';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';

export const REGISTER_FB_USER_REQUESTED = 'REGISTER_FB_USER_REQUESTED';
export const REGISTER_FB_USER_SUCCESS = 'REGISTER_FB_USER_SUCCESS';
export const REGISTER_FB_USER_FAILED = 'REGISTER_FB_USER_FAILED';

export const LOGIN_FACEBOOK_REQUESTED = 'LOGIN_FACEBOOK_REQUESTED';
export const LOGIN_FACEBOOK_SUCCESS = 'LOGIN_FACEBOOK_SUCCESS';
export const LOGIN_FACEBOOK_FAILED = 'LOGIN_FACEBOOK_FAILED';

export const FORGOT_PASSWORD_REQUESTED = 'FORGOT_PASSWORD_REQUESTED';
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';

export const RESET_PASSWORD_REQUESTED = 'RESET_PASSWORD_REQUESTED';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILED = 'RESET_PASSWORD_FAILED';

export const LOG_OUT = 'LOG_OUT';
